### ISSUE TITLE
Question (probably too early for this but eh)

### ISSUE THREAD

**Issue by RepellantMold** [Mega-Drive-Developers-Collective/Sonic-1-Prototype#10]
Could we document object SST's in this disassembly at some point?

**Comment by Awuwunya** [comment]
yes, this is the intention, this should be able to be accomplished via IDA in a reasonable manner, I just hadn't had time to think about it

**Comment by RandomName-proj** [comment]
Sorry for Offtop: It's possible to Name address register offsets via Ida Pro?

**Comment by Awuwunya** [comment]
yes, you can at least use structures, eg: Object.property, but IIRC IDA should ve able to use equates which would be more ideal in this case

**Comment by DeltaWooloo** [comment]
Should we make a separate constant.asm file like how they did it in the GitHub disassembles?

**Comment by RepellantMold** [comment]
that's how i'd intend to do that

**Comment by RandomName-proj** [comment]
I think it depends on how and where ida pro can do equates

**Comment by DeltaWooloo** [comment]
> that's how i'd intend to do that

Thanks. Please give that a go so it can be easier for me to find any missing bits I need to label in the disassembly. Also, I should be pushing a big label commit, I'll do a pull request in a hour or two.

**Comment by MD-Devs** [comment]
Prototyping this in 10096fbfef3b03b60b98de7851dbd41be737aa9a
Unfortunately IDA does not output these equates to a LST file so they won't update automatically. RIP. However this should be easy enough to do by hand.

**Comment by lavagaming1** [comment]
hey can you add me here so i can help with doucuments ?

**Comment by RandomName-proj** [comment]
Wdym add? Everybody, except Aurora just make pull requests, and Aurora checks, edits them if needed and commits them to repository.

**Comment by lavagaming1** [comment]
> Wdym add? Everybody, except Aurora just make pull requests, and Aurora checks, edits them if needed and commits them to repository.

i mean i want to help

**Comment by RandomName-proj** [comment]
Well, help is appreciated. If you want to add your changes to disassembly you need to make pull request as I said before. To make pull request you need: make a fork of this repository, commit your changes into your fork, compare your repository with upstream repository and there will be pull request button to which you need to press obivously.

**Comment by lavagaming1** [comment]
> Well, help is appreciated. If you want to add your changes to disassembly you need to make pull request as I said before. To make pull request you need: make a fork of this repository, commit your changes into your fork, compare your repository with upstream repository and there will be pull request button to which you need to press obivously.

ok sure thing
